# Generated by Django 2.2.28 on 2023-02-08 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0005_auto_20230208_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='views',
            field=models.IntegerField(default=1),
        ),
    ]
